### ISSUE TITLE
Anchor and reference for same node not working

### ISSUE THREAD

**Issue by ubersmart** [ptarjan/online-yaml-parser#6]
Consider below YAML
```
- just: write some
- yaml:     
    node1:
      type: type1
      properties: &node1_prop
        role: management
        ip_version: ipv4

    node2:
      type: type2
      properties: &node2_prop *node1_prop 
      requirements:
        - dependency: node1

    node3:
      type: type3
      properties: *node2_prop
      requirements:
        - dependency: node2
```
Parsing above throws error, while it should be parsed successfully.
